### ISSUE TITLE
能否增加retrofit2的拦截?

### ISSUE THREAD

**Issue by dfaofeng** [siyujie/OkHttpLogger-Frida#12]
目前看到很多主流的app也在用这个框架,能否适配呢?

**Comment by siyujie** [comment]
Retrofit网络请求的核心也是使用okhttp，理论上可以直接兼容Retrofit库的。如果不能拦截，可以再提交一下问题。

**Comment by dfaofeng** [comment]
还有一个问题.能否判断返回值是否为json字符串,并且格式化好,直接粗暴的\n后期提取好麻烦阿
