### ISSUE TITLE
使用最新的okhttp4.10.0有问题闪退，但是在3.12.0就没问题

### ISSUE THREAD

**Issue by Zooc** [siyujie/OkHttpLogger-Frida#9]
创建一个简单的demo，引用okhtt3版本3.12.0， 可以正常使用和获取数据，但是当引用版本为最新，例如4.10.0后，就闪退了。
打上日志后发现是在
function getFieldValue(object, fieldName)
方法里面的
var FieldClazz = Java.use(fieldValue.$className)
出问题了，直接闪退，即使使用try都不行捕获日志。此时field.$className的值为okhttp3.Headers（两个版本的值都是一样，不知道最新版为什么运行到这里会闪退）。

**Comment by siyujie** [comment]
你好，能发一下样本APP吗？我这边demo 中引入`implementation("com.squareup.okhttp3:okhttp:4.10.0-RC1")`可以正常抓到包。
留下apk下载链接或者发送到邮箱: s278149506@gmail.com 。
谢谢！

**Comment by Zooc** [comment]
不好意思，可能是使用的模拟器的问题，我之前是用了网易的mumu模拟器（系统总是显示6.0.1），总是会出这个问题，然后我用真机去弄（系统10）就没有这个问题了，后面我可能都会用真机去弄了。
